# Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_I2C=y
CONFIG_SSD1306=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y

# nice!oled
CONFIG_NICE_OLED_ON=y

# Main / central side widgets
CONFIG_NICE_OLED_WIDGET_LAYER=y
CONFIG_NICE_OLED_WIDGET_LAYER_CUSTOM_X=0
CONFIG_NICE_OLED_WIDGET_LAYER_CUSTOM_Y=146

CONFIG_NICE_OLED_WIDGET_WPM=n
CONFIG_NICE_OLED_WIDGET_WPM_NUMBER=n
CONFIG_NICE_OLED_WIDGET_WPM_SPEEDOMETER=n

CONFIG_NICE_OLED_WIDGET_HID_INDICATORS=y
CONFIG_ZMK_HID_INDICATORS=y
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS=y

# Peripheral side animation: choose one
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_GEM=n

# Stability
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_PRIORITY=5
CONFIG_LV_Z_MEM_POOL_SIZE=8192

# RGB underglow
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_WS2812_STRIP=n
